const { withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

/**
 * Restores cleartext HTTP to the Metro dev server for debug builds.
 *
 * A dependency (the Tapsell SDK, as of the mediation adapter added in
 * `withTapsellAdapters`) contributes `android:networkSecurityConfig` to the
 * merged manifest. On API 24+ that config takes precedence over the debug
 * manifest's `android:usesCleartextTraffic="true"`, so the dev client can no
 * longer load a bundle over plain HTTP and dies with:
 *
 *   java.net.UnknownServiceException: CLEARTEXT communication to <lan-ip>
 *   not permitted by network security policy
 *
 * Pointing the *debug* variant at a permissive config of our own fixes the dev
 * loop without touching release builds, which keep the library's stricter
 * policy. `android/` is regenerated by prebuild, hence a plugin rather than a
 * hand edit.
 */
const CONFIG_NAME = "tally_debug_network_security_config";

const CONFIG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Debug only. Generated by plugins/withDebugCleartext.js — do not edit. -->
<network-security-config>
  <base-config cleartextTrafficPermitted="true">
    <trust-anchors>
      <certificates src="system" />
      <certificates src="user" />
    </trust-anchors>
  </base-config>
</network-security-config>
`;

module.exports = function withDebugCleartext(config) {
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const root = cfg.modRequest.platformProjectRoot;
      const debugDir = path.join(root, "app", "src", "debug");

      const xmlDir = path.join(debugDir, "res", "xml");
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, `${CONFIG_NAME}.xml`), CONFIG_XML);

      const manifestPath = path.join(debugDir, "AndroidManifest.xml");
      const before = fs.readFileSync(manifestPath, "utf8");
      if (before.includes(CONFIG_NAME)) return cfg;

      // The merger refuses a conflicting attribute unless the override is
      // declared, so `tools:replace` has to name it too.
      const withReplace = before.replace(/tools:replace="([^"]*)"/, (match, list) =>
        list.includes("android:networkSecurityConfig")
          ? match
          : `tools:replace="${list},android:networkSecurityConfig"`,
      );
      if (withReplace === before) {
        throw new Error(
          "withDebugCleartext: no tools:replace attribute in app/src/debug/AndroidManifest.xml; " +
            "cannot override android:networkSecurityConfig safely.",
        );
      }

      const withAttr = withReplace.replace(
        /<application\b/,
        `<application\n        android:networkSecurityConfig="@xml/${CONFIG_NAME}"`,
      );
      if (withAttr === withReplace) {
        throw new Error(
          "withDebugCleartext: no <application> tag in app/src/debug/AndroidManifest.xml.",
        );
      }

      fs.writeFileSync(manifestPath, withAttr);
      return cfg;
    },
  ]);
};
