const { withAppBuildGradle, withProjectBuildGradle } = require("expo/config-plugins");

/**
 * Tapsell Mediation ships the mediation core but no ad-network adapters: the
 * npm package declares only `ir.tapsell:tapsell-reactnative`, so a build
 * without this plugin resolves `ir.tapsell.mediation:{di,tapsell-reactnative}`
 * and nothing that can actually fill an ad.
 *
 * The failure mode is silent, not loud: mediation accepts the request (logcat
 * shows "New ad request was received") and then, with no adapter in the
 * waterfall to route it to, never calls back at all — no fill event, no error.
 * `tapsellProvider.show()` would hang forever without its `REQUEST_TIMEOUT_MS`
 * watchdog.
 *
 * `android/` is regenerated by prebuild, so the dependency has to be injected
 * here rather than edited into `android/app/build.gradle` by hand.
 *
 * Coordinates live under the `ir.tapsell.mediation.adapter` group, one
 * artifact per ad network, each with a per-framework variant — React Native
 * needs the `-reactnative` one. Tapsell's *own* network is published as
 * `legacy` (there is no `tapsell` adapter); third-party networks enabled in
 * the zone's waterfall on developer.tapsell.ir need their own line here, e.g.
 * `admob-reactnative`, `applovin-reactnative`, `unityads-reactnative`.
 * Versions track the mediation core (1.3.0).
 */
const ADAPTERS = ["ir.tapsell.mediation.adapter:legacy-reactnative:1.3.0"];

/**
 * Tapsell publishes to its own maven, and the npm package declares that repo
 * only inside its own module (`.../tapsell/android/build.gradle`). The app
 * module resolves against the root `allprojects` block instead, which knows
 * nothing about it — so adding the adapter dependency without this repo fails
 * the build at resolution.
 */
const TAPSELL_MAVEN = "https://maven.tapsell.ir";

function addTapsellMaven(config) {
  return withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error(
        `withTapsellAdapters: expected a Groovy android/build.gradle, got '${cfg.modResults.language}'.`,
      );
    }
    if (cfg.modResults.contents.includes(TAPSELL_MAVEN)) return cfg;

    const before = cfg.modResults.contents;
    cfg.modResults.contents = before.replace(
      /(allprojects\s*\{\s*repositories\s*\{)/,
      `$1\n    maven { url = uri('${TAPSELL_MAVEN}') }`,
    );
    if (cfg.modResults.contents === before) {
      throw new Error(
        "withTapsellAdapters: no 'allprojects { repositories {' block found in android/build.gradle; " +
          `could not add ${TAPSELL_MAVEN}.`,
      );
    }
    return cfg;
  });
}

module.exports = function withTapsellAdapters(config) {
  return withAppBuildGradle(addTapsellMaven(config), (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error(
        `withTapsellAdapters: expected a Groovy app/build.gradle, got '${cfg.modResults.language}'.`,
      );
    }

    for (const adapter of ADAPTERS) {
      if (cfg.modResults.contents.includes(adapter)) continue;

      const before = cfg.modResults.contents;
      cfg.modResults.contents = before.replace(
        /^dependencies\s*\{/m,
        (match) => `${match}\n    implementation "${adapter}"`,
      );

      // Fail loudly. A no-op replace would ship a build that looks configured
      // and then hangs on every ad request — the exact silence this plugin
      // exists to prevent.
      if (cfg.modResults.contents === before) {
        throw new Error(
          `withTapsellAdapters: no top-level 'dependencies {' block found in app/build.gradle; could not add ${adapter}.`,
        );
      }
    }

    return cfg;
  });
};
