const { withAppBuildGradle, withProjectBuildGradle } = require("expo/config-plugins");

/**
 * Tapsell Mediation ships the mediation core but no ad-network adapters: the
 * npm package declares only `ir.tapsell:tapsell-reactnative`, so a build
 * without this plugin resolves `ir.tapsell.mediation:{di,tapsell-reactnative}`
 * and nothing that can actually fill an ad.
 *
 * The failure mode is silent, not loud: mediation accepts the request (logcat
 * shows "New ad request was received") and then, with no adapter in the
 * waterfall to route it to, never calls back at all — no fill event, no error.
 * `tapsellProvider.show()` would hang forever without its `REQUEST_TIMEOUT_MS`
 * watchdog.
 *
 * `android/` is regenerated by prebuild, so the dependency has to be injected
 * here rather than edited into `android/app/build.gradle` by hand.
 *
 * Coordinates live under the `ir.tapsell.mediation.adapter` group, one
 * artifact per ad network, each with a per-framework variant — React Native
 * needs the `-reactnative` one. Tapsell's *own* network is published as
 * `legacy` (there is no `tapsell` adapter); third-party networks enabled in
 * the zone's waterfall on developer.tapsell.ir need their own line here, e.g.
 * `admob-reactnative`, `applovin-reactnative`, `unityads-reactnative`.
 * Versions track the mediation core (1.3.0).
 */
const ADAPTERS = ["ir.tapsell.mediation.adapter:legacy-reactnative:1.3.0"];

/**
 * Tapsell publishes to its own maven, and the npm package declares that repo
 * only inside its own module (`.../tapsell/android/build.gradle`). The app
 * module resolves against the root `allprojects` block instead, which knows
 * nothing about it — so adding the adapter dependency without this repo fails
 * the build at resolution.
 */
const TAPSELL_MAVEN = "https://maven.tapsell.ir";

/**
 * Confine that repo to Tapsell's own coordinates.
 *
 * Unfiltered, `maven.tapsell.ir` sits first in `allprojects { repositories }`
 * and is therefore the first host Gradle asks for EVERY dependency of EVERY
 * module. It is served from Iran (45.94.254.10 / 45.94.255.10), so from an EAS
 * builder abroad the request does not come back a clean 404 — it hangs, and
 * Gradle treats a connect timeout as fatal rather than falling through to the
 * next repo in the list.
 *
 * That is exactly how versionCode 9 died:
 * `com.github.cafebazaar.Poolakey:poolakey:2.2.0` is published on JitPack,
 * which prebuild declares three lines further down, but resolution never got
 * that far —
 *
 *     Could not GET 'https://maven.tapsell.ir/com/github/cafebazaar/Poolakey/…'
 *     Connect to maven.tapsell.ir:443 … failed: Connect timed out
 *
 * With the filter, only `ir.tapsell*` artifacts ever touch that host, so a slow
 * or unreachable Iranian mirror can no longer take down the resolution of
 * dependencies that have nothing to do with Tapsell. It also drops an
 * intercontinental round trip from every other artifact's lookup.
 *
 * Backslashes are doubled because this lands inside a Groovy single-quoted
 * string, which processes escape sequences — a lone `\.` is an illegal escape
 * and fails at configuration time.
 */
const TAPSELL_GROUP_REGEX = String.raw`ir\\.tapsell(\\..*)?`;

function addTapsellMaven(config) {
  return withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error(
        `withTapsellAdapters: expected a Groovy android/build.gradle, got '${cfg.modResults.language}'.`,
      );
    }
    if (cfg.modResults.contents.includes(TAPSELL_MAVEN)) return cfg;

    const repoBlock = [
      "    maven {",
      `      url = uri('${TAPSELL_MAVEN}')`,
      `      content { includeGroupByRegex '${TAPSELL_GROUP_REGEX}' }`,
      "    }",
    ].join("\n");

    const before = cfg.modResults.contents;
    cfg.modResults.contents = before.replace(
      /(allprojects\s*\{\s*repositories\s*\{)/,
      `$1\n${repoBlock}`,
    );
    if (cfg.modResults.contents === before) {
      throw new Error(
        "withTapsellAdapters: no 'allprojects { repositories {' block found in android/build.gradle; " +
          `could not add ${TAPSELL_MAVEN}.`,
      );
    }
    return cfg;
  });
}

module.exports = function withTapsellAdapters(config) {
  return withAppBuildGradle(addTapsellMaven(config), (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error(
        `withTapsellAdapters: expected a Groovy app/build.gradle, got '${cfg.modResults.language}'.`,
      );
    }

    for (const adapter of ADAPTERS) {
      if (cfg.modResults.contents.includes(adapter)) continue;

      const before = cfg.modResults.contents;
      cfg.modResults.contents = before.replace(
        /^dependencies\s*\{/m,
        (match) => `${match}\n    implementation "${adapter}"`,
      );

      // Fail loudly. A no-op replace would ship a build that looks configured
      // and then hangs on every ad request — the exact silence this plugin
      // exists to prevent.
      if (cfg.modResults.contents === before) {
        throw new Error(
          `withTapsellAdapters: no top-level 'dependencies {' block found in app/build.gradle; could not add ${adapter}.`,
        );
      }
    }

    return cfg;
  });
};
